#!/usr/bin/env bash
# ── CPIP Raspberry Pi Fleet Deployer ──────────────────────────────────
# Flash, provision, and connect multiple Raspberry Pi devices to the
# CPIP mesh network using rpi-imager CLI and rpi-connect.
#
# This script automates the full lifecycle:
#   1. Flash SD cards with Raspberry Pi OS using rpi-imager --cli
#   2. Pre-configure WiFi, SSH, hostname, and CPIP settings
#   3. Install rpi-connect for remote browser access
#   4. Deploy CPIP server and mesh network
#
# Usage:
#   ./deploy-pi.sh scan                      List SD cards / NVMe drives
#   ./deploy-pi.sh flash <device> <node_id>  Flash + configure one Pi
#   ./deploy-pi.sh fleet <count>             Flash N nodes in sequence
#   ./deploy-pi.sh provision <ip> <node_id>  Provision a running Pi
#   ./deploy-pi.sh connect                   Set up rpi-connect on a Pi
#   ./deploy-pi.sh setup                     Full interactive setup
#
# Requirements:
#   - rpi-imager (sudo apt install rpi-imager)
#   - rpi-connect (on target Pi)
#   - SD card or NVMe SSD
#   - Internet connection
# ──────────────────────────────────────────────────────────────────────
set -euo pipefail

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SERVER_SRC="${SCRIPT_DIR}/server.py"
CLI_SRC="${SCRIPT_DIR}/cpip"

# Defaults
WIFI_SSID="${WIFI_SSID:-}"
WIFI_PASS="${WIFI_PASS:-}"
WIFI_COUNTRY="${WIFI_COUNTRY:-US}"
PI_USER="${PI_USER:-pi}"
PI_PASS="${PI_PASS:-cpip}"
CONNECT_AUTH_KEY="${CONNECT_AUTH_KEY:-}"
OS_IMAGE="${OS_IMAGE:-}"  # empty = use default RPi OS Lite
NODE_PREFIX="${NODE_PREFIX:-cpip-node}"
BASE_HTTP_PORT=4180
BASE_MESH_PORT=4191

info()  { printf "${CYAN}[*]${NC} %s\n" "$1"; }
ok()    { printf "${GREEN}[OK]${NC} %s\n" "$1"; }
warn()  { printf "${YELLOW}[!]${NC} %s\n" "$1"; }
fail()  { printf "${RED}[X]${NC} %s\n" "$1"; exit 1; }

# ── Check prerequisites ──────────────────────────────────────────────
check_deps() {
    local missing=()
    for cmd in rpi-imager python3; do
        command -v "$cmd" &>/dev/null || missing+=("$cmd")
    done
    if [ ${#missing[@]} -gt 0 ]; then
        warn "Missing tools: ${missing[*]}"
        info "Installing rpi-imager..."
        sudo apt update -qq && sudo apt install -y -qq rpi-imager 2>/dev/null || \
            fail "Cannot install rpi-imager. Install manually: sudo apt install rpi-imager"
    fi
}

# ── Scan for removable storage ────────────────────────────────────────
cmd_scan() {
    info "Scanning for removable storage devices..."
    echo ""
    echo -e "${BLUE}Device              Size    Type${NC}"
    echo "──────────────────────────────────────────────"

    # Look for SD cards and USB drives
    local devs=()
    for dev in /dev/sd? /dev/mmcblk? /dev/nvme?n?; do
        [ -b "$dev" ] || continue
        local size=$(lsblk -dno SIZE "$dev" 2>/dev/null | xargs)
        local model=$(lsblk -dno MODEL "$dev" 2>/dev/null | xargs)
        local removable=$(cat /sys/block/$(basename "$dev")/removable 2>/dev/null || echo "0")
        local ro=$(cat /sys/block/$(basename "$dev")/ro 2>/dev/null || echo "0")

        if [ "$removable" = "1" ] || echo "$dev" | grep -q "mmcblk\|nvme"; then
            printf "  %-20s %-8s %s\n" "$dev" "$size" "${model:-unknown}"
            devs+=("$dev")
        fi
    done

    if [ ${#devs[@]} -eq 0 ]; then
        warn "No removable storage found. Insert an SD card or USB drive."
    else
        echo ""
        echo -e "${GREEN}Found ${#devs[@]} device(s)${NC}"
    fi
}

# ── Generate first-run provisioning script ────────────────────────────
generate_firstrun() {
    local node_id="$1"
    local http_port=$((BASE_HTTP_PORT + ${node_id##*-}))
    local mesh_port=$((BASE_MESH_PORT + ${node_id##*-}))
    local hostname="${NODE_PREFIX}-${node_id##*-}"
    local output="$2"

    cat << 'FIRSTRUN_HEADER' > "$output"
#!/bin/bash
# CPIP First-Run Provisioning Script
# Generated by deploy-pi.sh — DO NOT EDIT
set -euo pipefail

LOG="/var/log/cpip-provision.log"
exec > >(tee -a "$LOG") 2>&1

echo "=== CPIP Provisioning started at $(date) ==="

# Wait for network
echo "Waiting for network..."
for i in $(seq 1 30); do
    ping -c1 -W1 8.8.8.8 &>/dev/null && break
    sleep 2
done

# System update
echo "Updating system..."
apt-get update -qq
apt-get upgrade -y -qq

# Install dependencies
echo "Installing dependencies..."
apt-get install -y -qq python3 python3-pip python3-venv git curl \
    gcc g++ make libffi-dev libssl-dev \
    rpi-connect-lite

FIRSTRUN_HEADER

    cat << FIRSTRUN_PROVISION >> "$output"

# ── Configure hostname ────────────────────────────────────────────────
echo "Setting hostname to ${hostname}..."
hostnamectl set-hostname "${hostname}"

# ── Install CPIP ──────────────────────────────────────────────────────
echo "Installing CPIP server..."
mkdir -p /opt/cpip
cat > /opt/cpip/server.py << 'CPIP_SERVER_EOF'
$(cat "$SERVER_SRC")
CPIP_SERVER_EOF
chmod +x /opt/cpip/server.py

# Install CLI
cp "${CLI_SRC}" /usr/local/bin/cpip
chmod +x /usr/local/bin/cpip

# Install web dashboard
if [ -d "${SCRIPT_DIR}/web" ]; then
    mkdir -p /opt/cpip/web
    cp -r "${SCRIPT_DIR}/web/"* /opt/cpip/web/
fi

# ── Install Python dependencies ───────────────────────────────────────
echo "Installing Python packages..."
pip3 install --break-system-packages cryptography numpy 2>/dev/null || \
    pip3 install cryptography numpy

# ── Install rpi-connect ───────────────────────────────────────────────
echo "Enabling Raspberry Pi Connect..."
systemctl enable rpi-connect 2>/dev/null || true
systemctl start rpi-connect 2>/dev/null || true
${CONNECT_AUTH_KEY:+rpi-connect signin "${CONNECT_AUTH_KEY}"}

# ── Configure systemd service ─────────────────────────────────────────
echo "Creating CPIP service..."
cat << 'SVCEOF' > /etc/systemd/system/cpip.service
[Unit]
Description=CPIP v4.0.1 — Coffee Pot Internet Protocol
After=network.target

[Service]
Type=simple
Environment=CPIP_DEVICE=hyper-text
Environment=CPIP_BIND=0.0.0.0
Environment=CPIP_PORT=${http_port}
Environment=CPIP_MESH=1
Environment=CPIP_MESH_PORT=${mesh_port}
Environment=CPIP_COVERT=1
Environment=CPIP_COVER_TRAFFIC=1
Environment=CPIP_SSL=1
Environment=CPIP_SSL_AUTO=1
Environment=CPIP_HTTP_REDIRECT=0
Environment=CPIP_NTP=1
Environment=CPIP_GPIO=1
ExecStart=/usr/bin/python3 /opt/cpip/server.py
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
SVCEOF

systemctl daemon-reload
systemctl enable cpip.service
systemctl start cpip.service

# ── Register identity and DNS ─────────────────────────────────────────
sleep 5
POT_ID=\$(python3 -c "import hashlib; print(hashlib.sha256(b'${hostname}:${http_port}').hexdigest()[:8])" 2>/dev/null || echo "")
if [ -n "\$POT_ID" ]; then
    curl -sk -X POST "https://localhost:${http_port}/cpip/identity/publish" \\
        -H "Content-Type: application/json" -d '{}' 2>/dev/null || true
    curl -sk -X POST "https://localhost:${http_port}/cpip/dns/register" \\
        -H "Content-Type: application/json" \\
        -d "{\"name\": \"${hostname}.pot\"}" 2>/dev/null || true
fi

echo ""
echo "══════════════════════════════════════════════════════"
echo "  CPIP v3.0 provisioned on ${hostname}"
echo "  HTTP : ${http_port} | Mesh UDP : ${mesh_port}"
echo "  Pot ID : \$POT_ID"
echo "  Service: systemctl status cpip"
echo "  Logs   : journalctl -u cpip -f"
echo "══════════════════════════════════════════════════════"
echo ""
echo "=== CPIP Provisioning completed at \$(date) ==="

# Reboot to apply hostname
reboot
FIRSTRUN_PROVISION
    chmod +x "$output"
    ok "First-run script generated: $output"
}

# ── Flash a single device ─────────────────────────────────────────────
cmd_flash() {
    local device="${1:-}"
    local node_id="${2:-0}"

    [ -z "$device" ] && fail "Usage: $0 flash <device> <node_id>"
    [ ! -b "$device" ] && fail "Device $device not found"

    local node_num=${node_id##*-}
    [ -z "$node_num" ] && node_num="$node_id"
    local hostname="${NODE_PREFIX}-${node_num}"
    local http_port=$((BASE_HTTP_PORT + node_num))
    local mesh_port=$((BASE_MESH_PORT + node_num))

    echo -e "${CYAN}══════════════════════════════════════════════════════${NC}"
    echo -e "${CYAN}  CPIP Pi Flasher — Node $node_num${NC}"
    echo -e "${CYAN}══════════════════════════════════════════════════════${NC}"
    echo ""
    echo "  Device    : $device"
    echo "  Hostname  : $hostname"
    echo "  HTTP Port : $http_port"
    echo "  Mesh Port : $mesh_port"
    echo "  WiFi SSID : ${WIFI_SSID:-'(not set)'}"
    echo ""

    # Generate first-run script
    local firstrun="/tmp/cpip-firstrun-${node_num}.sh"
    info "Generating first-run provisioning script..."
    generate_firstrun "$node_id" "$firstrun"

    # Build rpi-imager command
    local img_args=()
    if [ -n "$OS_IMAGE" ]; then
        img_args+=("$OS_IMAGE")
    else
        img_args+=("raspios_lite_arm64")
    fi

    info "Flashing $device with Raspberry Pi OS Lite..."

    # Use rpi-imager --cli
    if [ -n "$OS_IMAGE" ]; then
        sudo rpi-imager --cli \
            --first-run-script "$firstrun" \
            "$OS_IMAGE" "$device"
    else
        # Use default RPi OS via imager
        sudo rpi-imager --cli \
            --first-run-script "$firstrun" \
            "raspios_lite_arm64" "$device"
    fi

    ok "Flash complete for $device"
    echo ""
    echo -e "${GREEN}  Next steps:${NC}"
    echo "  1. Insert $device into a Raspberry Pi"
    echo "  2. Power on — the Pi will auto-provision on first boot"
    echo "  3. Wait ~3 minutes for provisioning to complete"
    echo "  4. Pi will reboot with CPIP running"
    echo ""
    if [ -n "$CONNECT_AUTH_KEY" ]; then
        echo "  Connect auth key will be applied automatically."
        echo "  Check https://connect.raspberrypi.com after boot."
    else
        echo "  To set up rpi-connect, run on the Pi:"
        echo "    rpi-connect signin"
    fi
    echo ""

    rm -f "$firstrun"
}

# ── Flash N nodes ──────────────────────────────────────────────────────
cmd_fleet() {
    local count="${1:-3}"

    info "Scanning for removable storage..."
    local devices=()
    while IFS= read -r line; do
        local dev=$(echo "$line" | awk '{print $1}')
        [ -b "$dev" ] && devices+=("$dev")
    done < <(lsblk -dno NAME,SIZE,TYPE 2>/dev/null | grep "rom" | awk '{print "/dev/"$1, $2}')

    # Fallback: manual detection
    if [ ${#devices[@]} -eq 0 ]; then
        echo ""
        warn "No removable storage auto-detected."
        echo "Enter device paths manually (one per line, empty to finish):"
        while true; do
            read -r -p "  Device: " dev
            [ -z "$dev" ] && break
            [ -b "$dev" ] && devices+=("$dev") || warn "$dev not found"
        done
    fi

    if [ ${#devices[@]} -lt "$count" ]; then
        warn "Found ${#devices[@]} device(s) but requested $count nodes."
        warn "Will flash ${#devices[@]} node(s). Insert more SD cards for the rest."
        count=${#devices[@]}
    fi

    if [ "$count" -eq 0 ]; then
        fail "No devices to flash."
    fi

    echo ""
    echo -e "${CYAN}══════════════════════════════════════════════════════${NC}"
    echo -e "${CYAN}  CPIP Fleet Flasher — $count nodes${NC}"
    echo -e "${CYAN}══════════════════════════════════════════════════════${NC}"
    echo ""

    for i in $(seq 0 $((count - 1))); do
        local dev="${devices[$i]}"
        local node_id="$((i + 1))"
        echo -e "${BLUE}── Flashing node $node_id to $dev ──${NC}"
        cmd_flash "$dev" "$node_id"
        echo ""
        if [ "$i" -lt $((count - 1)) ]; then
            echo "Insert next SD card and press Enter to continue..."
            read -r
        fi
    done

    echo ""
    echo -e "${GREEN}══════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}  Fleet flash complete! $count nodes provisioned${NC}"
    echo -e "${GREEN}══════════════════════════════════════════════════════${NC}"
    echo ""
    echo "  Node layout:"
    for i in $(seq 1 $count); do
        local hp=$((BASE_HTTP_PORT + i))
        local mp=$((BASE_MESH_PORT + i))
        echo "    Node $i: HTTP :$hp | Mesh UDP :$mp | ${NODE_PREFIX}-${i}"
    done
    echo ""
    echo "  After all nodes boot, run: $0 mesh-setup"
}

# ── Provision a running Pi over SSH ───────────────────────────────────
cmd_provision() {
    local host="${1:-}"
    local node_id="${2:-1}"

    [ -z "$host" ] && fail "Usage: $0 provision <ip_or_hostname> <node_id>"

    local node_num="${node_id##*-}"
    [ -z "$node_num" ] && node_num="$node_id"
    local hostname="${NODE_PREFIX}-${node_num}"
    local http_port=$((BASE_HTTP_PORT + node_num))
    local mesh_port=$((BASE_MESH_PORT + node_num))

    info "Provisioning $host as node $node_num ($hostname)..."

    # Copy server files
    scp "$SERVER_SRC" "${PI_USER}@${host}:/tmp/server.py" || fail "Cannot copy server.py"
    scp "$CLI_SRC" "${PI_USER}@${host}:/tmp/cpip" 2>/dev/null || true
    [ -d "${SCRIPT_DIR}/web" ] && \
        scp -r "${SCRIPT_DIR}/web" "${PI_USER}@${host}:/tmp/web" 2>/dev/null || true

    # Run remote provisioning
    ssh "${PI_USER}@${host}" bash << REMOTE
set -euo pipefail
sudo mv /tmp/server.py /opt/cpip/server.py
sudo chmod +x /opt/cpip/server.py
[ -f /tmp/cpip ] && sudo cp /tmp/cpip /usr/local/bin/cpip && sudo chmod +x /usr/local/bin/cpip
[ -d /tmp/web ] && sudo cp -r /tmp/web /opt/cpip/
sudo mkdir -p /opt/cpip/web

# Install deps
sudo pip3 install --break-system-packages cryptography numpy 2>/dev/null || \
    sudo pip3 install cryptography numpy

# Install rpi-connect-lite
sudo apt install -y rpi-connect-lite 2>/dev/null || true
sudo systemctl enable rpi-connect 2>/dev/null || true

# Create service
sudo tee /etc/systemd/system/cpip.service > /dev/null << 'SVCEOF'
[Unit]
Description=CPIP v3.0 — Node ${node_num}
After=network.target
[Service]
Type=simple
Environment=CPIP_DEVICE=hyper-text
Environment=CPIP_PORT=${http_port}
Environment=CPIP_MESH=1
Environment=CPIP_MESH_PORT=${mesh_port}
Environment=CPIP_COVERT=1
Environment=CPIP_SSL=1
Environment=CPIP_SSL_AUTO=1
ExecStart=/usr/bin/python3 /opt/cpip/server.py
Restart=on-failure
RestartSec=5
[Install]
WantedBy=multi-user.target
SVCEOF

sudo systemctl daemon-reload
sudo systemctl enable cpip
sudo systemctl restart cpip

echo "Node $node_num provisioned. HTTP :${http_port} Mesh :${mesh_port}"
REMOTE

    ok "Node $node_num provisioned at $host"
}

# ── Set up rpi-connect on a remote Pi ─────────────────────────────────
cmd_connect() {
    local host="${1:-}"
    [ -z "$host" ] && fail "Usage: $0 connect <ip_or_hostname> [auth_key]"

    local auth_key="${2:-$CONNECT_AUTH_KEY}"

    info "Setting up Raspberry Pi Connect on $host..."

    ssh "${PI_USER}@${host}" bash << REMOTE
set -euo pipefail
sudo apt update -qq
sudo apt install -y rpi-connect-lite 2>/dev/null || sudo apt install -y rpi-connect
sudo systemctl enable rpi-connect
sudo systemctl start rpi-connect

${auth_key:+rpi-connect signin "${auth_key}"}

echo ""
echo "Connect status:"
rpi-connect status 2>/dev/null || echo "(service starting...)"
echo ""
echo "Link device at: https://connect.raspberrypi.com"
REMOTE

    ok "rpi-connect configured on $host"
}

# ── Set up mesh between nodes ─────────────────────────────────────────
cmd_mesh_setup() {
    info "Setting up mesh network bootstrap..."

    # Discover nodes on the network
    local gateway_ip=$(ip route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}')
    local subnet=$(echo "$gateway_ip" | sed 's/\.[0-9]*$/.0/24')

    info "Scanning subnet $subnet for CPIP nodes..."

    local nodes=()
    for i in $(seq 1 20); do
        local ip="${subnet%.*}.$((i + 1))"
        if curl -sk --connect-timeout 1 "https://${ip}:${BASE_HTTP_PORT}/cpip/status" &>/dev/null; then
            nodes+=("$ip")
            ok "Found node at $ip"
        fi
    done

    if [ ${#nodes[@]} -lt 2 ]; then
        warn "Found ${#nodes[@]} node(s). Need at least 2 for mesh."
        warn "Make sure all nodes are powered on and on the same network."
        return
    fi

    info "Connecting ${#nodes[@]} nodes into mesh..."

    # Tell each node to scan for peers
    for ip in "${nodes[@]}"; do
        curl -sk --connect-timeout 2 "https://${ip}:${BASE_HTTP_PORT}/cpip/mesh/peers" &>/dev/null || true
        sleep 1
    done

    sleep 5

    # Check mesh status
    echo ""
    echo -e "${BLUE}Mesh Status:${NC}"
    for ip in "${nodes[@]}"; do
        local peers=$(curl -sk "https://${ip}:${BASE_HTTP_PORT}/cpip/mesh/peers" 2>/dev/null | \
            python3 -c "import sys,json; print(len(json.load(sys.stdin).get('peers',{})))" 2>/dev/null || echo "?")
        echo "  $ip : $peers peers"
    done

    ok "Mesh setup complete. Nodes should discover each other automatically."
}

# ── Interactive full setup ─────────────────────────────────────────────
cmd_setup() {
    echo -e "${CYAN}══════════════════════════════════════════════════════${NC}"
    echo -e "${CYAN}  CPIP Raspberry Pi Fleet Setup Wizard${NC}"
    echo -e "${CYAN}══════════════════════════════════════════════════════${NC}"
    echo ""

    # WiFi configuration
    read -r -p "WiFi SSID (empty for no WiFi): " WIFI_SSID
    if [ -n "$WIFI_SSID" ]; then
        read -r -s -p "WiFi Password: " WIFI_PASS
        echo ""
        read -r -p "WiFi Country [US]: " WIFI_COUNTRY
        WIFI_COUNTRY="${WIFI_COUNTRY:-US}"
    fi

    # Node count
    read -r -p "Number of nodes to deploy [3]: " node_count
    node_count="${node_count:-3}"

    # Connect auth key
    read -r -p "Raspberry Pi Connect auth key (optional, press Enter to skip): " CONNECT_AUTH_KEY

    echo ""
    echo "Configuration:"
    echo "  WiFi      : ${WIFI_SSID:-none}"
    echo "  Nodes     : $node_count"
    echo "  Connect   : ${CONNECT_AUTH_KEY:+configured}"
    echo ""

    # Scan for devices
    cmd_scan
    echo ""

    read -r -p "Ready to flash? [Y/n]: " confirm
    [ "$confirm" = "n" ] && return

    cmd_fleet "$node_count"
}

# ── Help ───────────────────────────────────────────────────────────────
cmd_help() {
    cat << 'HELP'
CPIP Raspberry Pi Fleet Deployer

Flash, provision, and connect multiple Raspberry Pis to the CPIP mesh network.

Usage:
  ./deploy-pi.sh scan                    List SD cards and NVMe drives
  ./deploy-pi.sh flash <device> <id>     Flash one SD card with CPIP node
  ./deploy-pi.sh fleet <count>           Flash N SD cards in sequence
  ./deploy-pi.sh provision <ip> <id>     Provision a running Pi via SSH
  ./deploy-pi.sh connect <ip> [key]      Set up rpi-connect on a Pi
  ./deploy-pi.sh mesh-setup              Discover and mesh-connect nodes
  ./deploy-pi.sh setup                   Interactive full setup wizard
  ./deploy-pi.sh help                    This message

Environment Variables:
  WIFI_SSID          WiFi network name
  WIFI_PASS          WiFi password
  WIFI_COUNTRY       WiFi country code (default: US)
  PI_USER            SSH username (default: pi)
  PI_PASS            SSH password (default: cpip)
  CONNECT_AUTH_KEY   rpi-connect auth key for remote access
  NODE_PREFIX        Hostname prefix (default: cpip-node)
  OS_IMAGE           Custom OS image path (default: raspios_lite_arm64)

Examples:
  # Flash one node
  ./deploy-pi.sh flash /dev/sdb 1

  # Flash 3 nodes with WiFi
  WIFI_SSID="MyNetwork" WIFI_PASS="secret" ./deploy-pi.sh fleet 3

  # Provision a Pi already on the network
  ./deploy-pi.sh provision 192.168.1.50 2

  # Set up rpi-connect for remote browser access
  ./deploy-pi.sh connect 192.168.1.50

  # Interactive wizard
  ./deploy-pi.sh setup

Node Layout:
  Node 1: HTTP :4180, Mesh UDP :4191
  Node 2: HTTP :4181, Mesh UDP :4192
  Node 3: HTTP :4182, Mesh UDP :4193
  ...

After deployment, access nodes via:
  - Local: https://<ip>:4180/dashboard
  - Remote: https://connect.raspberrypi.com (with rpi-connect)
HELP
}

case "${1:-help}" in
    scan)       cmd_scan ;;
    flash)      cmd_flash "${2:-}" "${3:-1}" ;;
    fleet)      cmd_fleet "${2:-3}" ;;
    provision)  cmd_provision "${2:-}" "${3:-1}" ;;
    connect)    cmd_connect "${2:-}" "${3:-}" ;;
    mesh-setup) cmd_mesh_setup ;;
    setup)      cmd_setup ;;
    help|*)     cmd_help ;;
esac
